name: 📦 Technical Contribution
description: Suggest a technical improvement or code contribution
title: "[Tech]: "
labels: [technical, help wanted]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Describe the proposed improvement or idea.
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why is this important?
      placeholder: Explain the reasoning or context.
